print('Comencemos con tu evaluación de servicio')
print('Vamos a realizar 3 tipos de saques : servicio seguro, servicio alto y servicio con salto')
print('Vas a necesitar un aro y un balon')
print('Ubica el aro en zona 1 del campo contrario y realiza 5 servicios seguros,  5 servicios altos y 5 servicios con saltos, todos dirogidos al aro')
BalSin1= int(input('¿Cuántos servicios seguros cayeron a dentro del aro? '))
BalSin2= int(input('¿Cuántos servicios altos cayeron a dentro del aro? '))
BalSin3= int(input('¿Cuántos servicios con salto cayeron a dentro del aro? '))
print('Vamos a repetir el proceso pero ubicando el aro en zona 6 del campo contrario.')
BalSin4= int(input('¿Cuántos servicios seguros cayeron a dentro del aro? '))
BalSin5= int(input('¿Cuántos servicios altos cayeron a dentro del aro? '))
BalSin6= int(input('¿Cuántos servicios con salto cayeron a dentro del aro? '))
print('Por último vamos a repetir el proceso pero ubicando el aro en zona 5 del campo contrario.')
BalSin7= int(input('¿Cuántos servicios seguros cayeron a dentro del aro? '))
BalSin8= int(input('¿Cuántos servicios altos cayeron a dentro del aro? '))
BalSin9= int(input('¿Cuántos servicios con salto cayeron a dentro del aro? '))
Dat1=float((BalSin1+BalSin2+BalSin3)*0.25)
Dat2=float((BalSin4+BalSin5+BalSin6)*0.25)
Dat3=float((BalSin7+BalSin8+BalSin9)*0.5)
PresicionServicio=int(((BalSin1+BalSin2+BalSin3+BalSin4+BalSin5+BalSin6+BalSin7+BalSin8+BalSin9)*100)/45)
EfectividadServicio=int(((Dat1+Dat2+Dat3)*10)/15)
print(PresicionServicio, EfectividadServicio)