print('Comencemos') 
print('Vamos a iniciar con tus estadísticas de recepción, vas a necesitar la ayuda de un compañero y un Hula Hula, tu compañero se ubicara en la posición 4 de la cancha y ubica el hula hula en la posición dos.' )
print('Tu compañero te lanzara 10 balones fáciles(Que vayan dirigidos a ti) esos balones los recibirás y contaras cuantos entran dentro del hula hula.' )
print('¿Cuántos balones cayeron dentro del aro?' )
balin1=float(input())
print('Listo vamos por la segunda prueba' )
print('Vas a repetir el ejercicio anterior, pero ahora tu compañero te debe rematar los balones en tu dirección' )
print('¿Cuántos balones cayeron dentro del aro?' )
balin2=float(input())
print('Listo vamos por la tercera prueba' )
print('Ahora los balones que tire tu compañero serán balones de rescate( Balones no dirigidos a ti) donde debes llegar a esos balones y contar cuantos caen dentro del aro')
print('¿Cuántos balones cayeron dentro del aro?' )
balin3=float(input())
pro1=float(balin1*0.2)
pro2=float(balin2*0.3)
pro3=float(balin3*0.5)
resR1=int(pro1+pro2+pro3)#ESte es el porcentaje de eficiencia
resR2=int(((balin1+balin2+balin3)*100)/30)#este es el porcentaje de precision
print(resR1)