print('Comencemos con las pruebas de voleo')
print('Para esta prueba vas a necesitar un compañero y un balón' )
print('Para la primera parte te vas a ubicar en 2 y  vas a pedir que te pasen el balón fácilmente para que en forma de voleo mandes el balón a posición 4 (El balón debe pasar a 50cm de la antena y debe ir en forma de parábola) lanzaras 15 balones y contaras cuantos pasaron por el punto de destino en una buena forma ( sin hacer doble golpe o levantamiento de balón)' )
print('¿Cuántos balones pasaron por la zona determinada?' )
balV1=int(input())
print('Ahora repetirás los lanzamientos de la misma manera pero ahora que el balón pase por la mitad de la malla a 30 cm de ella' )
balV2=int(input('¿Cuántos balones pasaron por la zona determinada? '))
print('La siguiente prueba será pasar los balones a posición 4 donde el balón debe pasar a 50 cm de la antena derecha de la malla y a 50 cm de la malla' )
balV3=int(input('¿Cuántos balones pasaron por la zona determinada? '))
#print('La siguiente prueba será pasar los balones a posición 4 donde el balón debe pasar a 50 cm de la antena derecha de la malla y a 50 cm de la malla') 
print('Ahora vas a pedir que te lancen los balones altos a un lugar diferente, los balones deben ser difíciles de pasar, vas a levantar 5 balones a 4, 5 balones a 3 y 5 balones a 2, cada uno en sus zonas determinadas anteriormente.' )
balV4=int(input('¿Cuántos balones pasaron por las zonas determinadas?'))
pro4=float(balV1*0.2)
pro5=float(balV2*0.2)
pro6=float(balV3*0.2)
pro7=float(balV4*0.4)
EfectividadVoleo=int(((pro4+pro5+pro6+pro7)*10)/15)
PresicionVoleo=int(((balV1+balV2+balV3+balV4)*100)/60)
print(EfectividadVoleo)
print(PresicionVoleo)